### PR TITLE
Fixed tests depending on Lucene 7.x Index to start using Lucene 8.x index ( OS 1.3 ) 

### PR DESCRIPTION
**Pull request by expani**
```
  1> [2024-12-18T18:00:46,449][INFO ][o.o.c.l.LuceneTests      ] [testCleanIndex] before test
  1> [2024-12-18T18:00:46,464][INFO ][o.o.c.l.LuceneTests      ] [testCleanIndex] after test
  1> [2024-12-18T18:00:46,468][INFO ][o.o.c.l.LuceneTests      ] [testReadSegmentInfosExtendedCompatibility] before test
  1> [2024-12-18T18:00:46,484][INFO ][o.o.c.l.LuceneTests      ] [testReadSegmentInfosExtendedCompatibility] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.common.lucene.LuceneTests.testReadSegmentInfosExtendedCompatibility" -Dtests.seed=84FE81AC7AFAE966 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-PF -Dtests.timezone=America/Belem -Druntime.java=23
  2> org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MockIndexInputWrapper(MemorySegmentIndexInput(path="/Users/anijainc/Desktop/GithubWorkspaces/OpenSearch_3_0_Lucene_10/OpenSearch/server/build/testrun/test/temp/org.opensearch.common.lucene.LuceneTests_84FE81AC7AFAE966-001/tempDir-002/segments_3")))): 8 (needs to be between 9 and 10). This version of Lucene only supports indexes created with release 9.0 and later.
        at __randomizedtesting.SeedInfo.seed([84FE81AC7AFAE966:E9D4BADB467D8764]:0)
        at app//org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:211)
        at app//org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:323)
        at app//org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:295)
        at app//org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:533)
        at app//org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:530)
        at app//org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:807)
        at app//org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:757)
        at app//org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:535)
        at app//org.opensearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:145)
        at app//org.opensearch.common.lucene.LuceneTests.testReadSegmentInfosExtendedCompatibility(LuceneTests.java:342)
  1> [2024-12-18T18:00:46,499][INFO ][o.o.c.l.LuceneTests      ] [testWrapLiveDocsNotExposeAbortedDocuments] before test
  1> [2024-12-18T18:00:46,512][INFO ][o.o.c.l.LuceneTests      ] [testWrapLiveDocsNotExposeAbortedDocuments] after test
```

Affected Tests using the zip containing ES 6.3 ( Lucene 7.x ) index to start using OS 1.3 ( Lucene 8.x ) index instead. 

```
./gradlew :server:test --tests "org.opensearch.common.lucene.LuceneTests.*"
./gradlew :server:test --tests "org.opensearch.index.engine.ReadOnlyEngineTests.*"
./gradlew :server:test --tests "org.opensearch.index.store.StoreTests.*"
```

Also, updated `SEARCHABLE_SNAPSHOT_EXTENDED_COMPATIBILITY_MINIMUM_VERSION` to the next version which is compatible with Lucene 8.x

### CODE REVIEW

**Comment by expani** [comment]
I generated the zip using OS 1.3.0 which has Lucene version as 8.10.1

I also tested usong ES 7.1.0 which has Lucene version as 8.0.0

Let me know if I should upload the index generated from ES 7.1.0 to keep the Lucene version as low as possible.

**Comment by reta** [comment]
> Let me know if I should upload the index generated from ES 7.1.0 to keep the Lucene version as low as possible.

Thanks @expani , I think having ES 7.1.0 won't hurt, please upload if you have time, thank you

**Comment by andrross** [comment]
> > Let me know if I should upload the index generated from ES 7.1.0 to keep the Lucene version as low as possible.
> 
> Thanks @expani , I think having ES 7.1.0 won't hurt, please upload if you have time, thank you

Lucene-level index compatibility is one thing, and testing an index written by Lucene 8.0 is not a bad idea. However, to actually use the searchable snapshot feature the system has to read and load all the index and snapshot metadata written by OpenSearch, and I think we'll be removing all the code that understands the ES versions and metadata. I think that means this feature will only in practice work with a snapshot written by OS 1.x even if it has the ability to read older Lucene indexes.

**Comment by reta** [comment]
> I think that means this feature will only in practice work with a snapshot written by OS 1.x even if it has the ability to read older Lucene indexes.

This is very valid statement, I agree, thank you @andrross

**Pull request merged**
